/**
 * Curated knowledge maps. These make output human-friendly and let us detect
 * popular plugins/themes/hosts from cheap public signals without brute-forcing
 * paths. Kept intentionally readable and easy to extend.
 */

/** REST API namespace (from /wp-json/) -> plugin slug + display name. */
export const REST_NAMESPACE_MAP: Record<string, { slug: string; name: string }> = {
  "wc/v3": { slug: "woocommerce", name: "WooCommerce" },
  "wc/v2": { slug: "woocommerce", name: "WooCommerce" },
  "wc/v1": { slug: "woocommerce", name: "WooCommerce" },
  "wc/store": { slug: "woocommerce", name: "WooCommerce" },
  "wc-analytics": { slug: "woocommerce", name: "WooCommerce" },
  "wc-admin": { slug: "woocommerce", name: "WooCommerce" },
  "contact-form-7/v1": { slug: "contact-form-7", name: "Contact Form 7" },
  "yoast/v1": { slug: "wordpress-seo", name: "Yoast SEO" },
  "rankmath/v1": { slug: "seo-by-rank-math", name: "Rank Math SEO" },
  "aioseo/v1": { slug: "all-in-one-seo-pack", name: "All in One SEO" },
  "elementor/v1": { slug: "elementor", name: "Elementor" },
  "jetpack/v4": { slug: "jetpack", name: "Jetpack" },
  "jetpack/v2": { slug: "jetpack", name: "Jetpack" },
  "wpml/v1": { slug: "sitepress-multilingual-cms", name: "WPML" },
  "pll/v1": { slug: "polylang", name: "Polylang" },
  "litespeed/v1": { slug: "litespeed-cache", name: "LiteSpeed Cache" },
  "wordfence/v1": { slug: "wordfence", name: "Wordfence Security" },
  "akismet/v1": { slug: "akismet", name: "Akismet" },
  "wpforms/v1": { slug: "wpforms-lite", name: "WPForms" },
  "give-api/v2": { slug: "give", name: "GiveWP" },
  "mailpoet/v1": { slug: "mailpoet", name: "MailPoet" },
  "gf/v2": { slug: "gravityforms", name: "Gravity Forms" },
  "ninja-forms/v1": { slug: "ninja-forms", name: "Ninja Forms" },
  "wp/v2/product": { slug: "woocommerce", name: "WooCommerce" },
  "wpcf7/v1": { slug: "contact-form-7", name: "Contact Form 7" },
  "wordpress-popular-posts/v2": { slug: "wordpress-popular-posts", name: "WordPress Popular Posts" },
  "tribe/events/v1": { slug: "the-events-calendar", name: "The Events Calendar" },
  "learnpress/v1": { slug: "learnpress", name: "LearnPress" },
  "lifterlms/v1": { slug: "lifterlms", name: "LifterLMS" },
  "tutor/v1": { slug: "tutor", name: "Tutor LMS" },
  "bricks/v1": { slug: "bricks", name: "Bricks Builder" },
  "oxygen/v1": { slug: "oxygen", name: "Oxygen Builder" },
  "elementor-pro/v1": { slug: "elementor-pro", name: "Elementor Pro" },
  "fluent-crm/v2": { slug: "fluent-crm", name: "FluentCRM" },
  "fluentform/v1": { slug: "fluentform", name: "Fluent Forms" },
  "wpcode/v1": { slug: "insert-headers-and-footers", name: "WPCode" },
  "wprocket/v1": { slug: "wp-rocket", name: "WP Rocket" },
  "buddypress/v1": { slug: "buddypress", name: "BuddyPress" },
  "bbpress/v1": { slug: "bbpress", name: "bbPress" },
  "surecart/v1": { slug: "surecart", name: "SureCart" },
  "dokan/v1": { slug: "dokan-lite", name: "Dokan" },
  "dokan/v2": { slug: "dokan-lite", name: "Dokan" },
  "ldlms/v2": { slug: "sfwd-lms", name: "LearnDash" },
  "give-api/v3": { slug: "give", name: "GiveWP" },
  "seopress/v1": { slug: "wp-seopress", name: "SEOPress" },
  "sureforms/v1": { slug: "sureforms", name: "SureForms" },
  "presto-player/v1": { slug: "presto-player", name: "Presto Player" },
  "forminator/v1": { slug: "forminator", name: "Forminator" },
  "mailchimp-for-woocommerce/v1": { slug: "mailchimp-for-woocommerce", name: "Mailchimp for WooCommerce" },
};

/**
 * Signatures found in the homepage HTML body that reveal a page builder /
 * framework / major plugin. `slug`/`name` add a plugin entry; `hint` is a note.
 */
export const HTML_SIGNATURES: { re: RegExp; hint: string; slug?: string; name?: string }[] = [
  { re: /elementor-frontend|data-elementor-type|\/elementor\//i, hint: "Page builder: Elementor", slug: "elementor", name: "Elementor" },
  { re: /wpb_row|js_composer|vc_row|wpb_wrapper/i, hint: "Page builder: WPBakery", slug: "js_composer", name: "WPBakery Page Builder" },
  { re: /\/beaver-builder|fl-builder/i, hint: "Page builder: Beaver Builder", slug: "beaver-builder-lite-version", name: "Beaver Builder" },
  { re: /brizy-/i, hint: "Page builder: Brizy", slug: "brizy", name: "Brizy" },
  { re: /et_pb_|\/Divi\/|id="et-/i, hint: "Theme/Builder: Divi", slug: "divi", name: "Divi" },
  { re: /brxe-|id="brx-content"/i, hint: "Page builder: Bricks", slug: "bricks", name: "Bricks Builder" },
  { re: /ct-section|oxy-|id="ct_default_style"/i, hint: "Page builder: Oxygen", slug: "oxygen", name: "Oxygen Builder" },
  { re: /wp-block-|has-global-padding|is-layout-flow|wp-container-/i, hint: "Uses the Gutenberg block editor" },
  { re: /woocommerce-page|wc-block|add_to_cart|woocommerce-js/i, hint: "WooCommerce store detected", slug: "woocommerce", name: "WooCommerce" },
  { re: /edd_download|easy-digital-downloads/i, hint: "Easy Digital Downloads store", slug: "easy-digital-downloads", name: "Easy Digital Downloads" },
  { re: /wpml-ls-|lang_sel|polylang/i, hint: "Multilingual site (WPML/Polylang)" },
  { re: /rev_slider|revslider|rs-module/i, hint: "Slider Revolution present", slug: "revslider", name: "Slider Revolution" },
  { re: /layerslider/i, hint: "LayerSlider present", slug: "LayerSlider", name: "LayerSlider" },
  { re: /swiper-container|swiper-wrapper/i, hint: "Uses Swiper sliders" },
  { re: /wpforms-|wpforms-container/i, hint: "WPForms detected", slug: "wpforms-lite", name: "WPForms" },
  { re: /gform_wrapper|gravity-forms/i, hint: "Gravity Forms detected", slug: "gravityforms", name: "Gravity Forms" },
  { re: /nf-form-|ninja-forms/i, hint: "Ninja Forms detected", slug: "ninja-forms", name: "Ninja Forms" },
  { re: /wpcf7|contact-form-7/i, hint: "Contact Form 7 detected", slug: "contact-form-7", name: "Contact Form 7" },
  { re: /elementskit-|ekit-widget/i, hint: "ElementsKit addons", slug: "elementskit-lite", name: "ElementsKit" },
];

/**
 * Path segments that appear after wp-content/plugins|themes/ but are build/
 * asset folders, not real slugs. Filtered out to avoid junk entries.
 */
export const SLUG_BLOCKLIST = new Set([
  "dist", "build", "assets", "vendor", "node_modules", "min", "src", "public",
]);

/**
 * Plugins/frameworks that declare themselves in a <meta name="generator">.
 * The capture group extracts the version when present (passive, exact).
 */
export const GENERATOR_SIGNATURES: { re: RegExp; slug: string; name: string }[] = [
  { re: /^elementor\s+([0-9][0-9a-z.\-]*)/i, slug: "elementor", name: "Elementor" },
  { re: /^woocommerce\s+([0-9][0-9a-z.\-]*)/i, slug: "woocommerce", name: "WooCommerce" },
  { re: /all\s*in\s*one\s*seo[^0-9]*([0-9][0-9a-z.\-]*)/i, slug: "all-in-one-seo-pack", name: "All in One SEO" },
  { re: /^powered by slider revolution\s*([0-9][0-9a-z.\-]*)?/i, slug: "revslider", name: "Slider Revolution" },
  { re: /site kit by google\s*([0-9][0-9a-z.\-]*)?/i, slug: "google-site-kit", name: "Site Kit by Google" },
  { re: /^redux\s+([0-9][0-9a-z.\-]*)/i, slug: "redux-framework", name: "Redux Framework" },
  { re: /^powered by visual composer|wpbakery/i, slug: "js_composer", name: "WPBakery Page Builder" },
  { re: /^tablepress\b/i, slug: "tablepress", name: "TablePress" },
  { re: /^gravity forms.*?([0-9][0-9a-z.\-]*)/i, slug: "gravityforms", name: "Gravity Forms" },
];

/**
 * Plugins that leave a distinctive HTML comment. Optional capture = version.
 */
export const COMMENT_SIGNATURES: { re: RegExp; slug: string; name: string }[] = [
  { re: /This site is optimized with the Yoast SEO plugin v?([0-9][0-9a-z.\-]*)/i, slug: "wordpress-seo", name: "Yoast SEO" },
  { re: /Optimized with the Yoast SEO Premium plugin v?([0-9][0-9a-z.\-]*)/i, slug: "wordpress-seo-premium", name: "Yoast SEO Premium" },
  { re: /Search Engine Optimization by Rank Math/i, slug: "seo-by-rank-math", name: "Rank Math SEO" },
  { re: /All in One SEO (?:Pro )?([0-9][0-9a-z.\-]*)\s*-\s*aioseo/i, slug: "all-in-one-seo-pack", name: "All in One SEO" },
  { re: /Performance optimized by W3 Total Cache/i, slug: "w3-total-cache", name: "W3 Total Cache" },
  { re: /Cached page generated by WP-Super-Cache/i, slug: "wp-super-cache", name: "WP Super Cache" },
  { re: /by WP Rocket|Optimized by WP Rocket/i, slug: "wp-rocket", name: "WP Rocket" },
  { re: /Page optimized by LiteSpeed Cache\s*([0-9][0-9a-z.\-]*)?/i, slug: "litespeed-cache", name: "LiteSpeed Cache" },
  { re: /WP Fastest Cache/i, slug: "wp-fastest-cache", name: "WP Fastest Cache" },
  { re: /Optimized by Autoptimize/i, slug: "autoptimize", name: "Autoptimize" },
  { re: /Powered by OptinMonster/i, slug: "optinmonster", name: "OptinMonster" },
  { re: /SEO by SEOPress\s*([0-9][0-9a-z.\-]*)?/i, slug: "wp-seopress", name: "SEOPress" },
  { re: /Optimized by NitroPack/i, slug: "nitropack", name: "NitroPack" },
  { re: /Optimized with the WP Smush/i, slug: "wp-smushit", name: "Smush" },
  { re: /Speed Optimizations by W3 Total Cache/i, slug: "w3-total-cache", name: "W3 Total Cache" },
];

/** HTTP header signatures for CDN / WAF / caching layers. */
export const HEADER_SIGNATURES: { product: string; test: (h: Record<string, string>) => boolean }[] = [
  { product: "Cloudflare", test: (h) => "cf-ray" in h || (h["server"] ?? "").includes("cloudflare") },
  { product: "Sucuri", test: (h) => "x-sucuri-id" in h || "x-sucuri-cache" in h },
  { product: "Fastly", test: (h) => "x-fastly-request-id" in h || (h["x-served-by"] ?? "").includes("cache") },
  { product: "Akamai", test: (h) => "x-akamai-transformed" in h || (h["server"] ?? "").toLowerCase().includes("akamai") },
  { product: "Amazon CloudFront", test: (h) => (h["via"] ?? "").includes("cloudfront") || "x-amz-cf-id" in h },
  { product: "LiteSpeed", test: (h) => (h["server"] ?? "").toLowerCase().includes("litespeed") || "x-litespeed-cache" in h },
  { product: "Wordfence", test: (h) => Object.keys(h).some((k) => k.startsWith("x-wf-")) },
  { product: "Varnish", test: (h) => "x-varnish" in h || (h["via"] ?? "").includes("varnish") },
  { product: "Imperva / Incapsula", test: (h) => "x-iinfo" in h || (h["x-cdn"] ?? "").toLowerCase().includes("incapsula") },
  { product: "StackPath", test: (h) => (h["server"] ?? "").toLowerCase().includes("stackpath") },
  { product: "BunnyCDN", test: (h) => (h["server"] ?? "").toLowerCase().includes("bunnycdn") || "cdn-requestid" in h },
  { product: "KeyCDN", test: (h) => (h["server"] ?? "").toLowerCase().includes("keycdn") },
  { product: "NitroPack", test: (h) => Object.keys(h).some((k) => k.startsWith("x-nitro")) },
  { product: "Ezoic", test: (h) => (h["server"] ?? "").toLowerCase().includes("ezoic") || "x-ezoic-cdn" in h },
  { product: "QUIC.cloud", test: (h) => (h["x-qc-cache"] ? true : false) || Object.keys(h).some((k) => k.startsWith("x-qc-")) },
];

/** HTTP header / cookie signatures for managed WordPress hosts. */
export const HOSTING_SIGNATURES: { product: string; test: (h: Record<string, string>) => boolean }[] = [
  { product: "Kinsta", test: (h) => "x-kinsta-cache" in h || Object.keys(h).some((k) => k.startsWith("x-kinsta")) },
  { product: "WP Engine", test: (h) => Object.keys(h).some((k) => k.startsWith("x-wpe")) || (h["x-powered-by"] ?? "").includes("WP Engine") },
  { product: "Pantheon", test: (h) => Object.keys(h).some((k) => k.startsWith("x-pantheon")) || "surrogate-key" in h },
  { product: "Flywheel", test: (h) => (h["server"] ?? "").toLowerCase().includes("flywheel") || "x-fw-serve" in h },
  { product: "Pressable", test: (h) => "x-ah-environment" in h },
  { product: "WordPress VIP", test: (h) => (h["x-powered-by"] ?? "").toLowerCase().includes("wordpress vip") },
  { product: "SiteGround", test: (h) => "x-sg-cachestatus" in h },
  { product: "Cloudways", test: (h) => (h["server"] ?? "").toLowerCase().includes("cloudways") || "x-cw-cache" in h },
  { product: "GoDaddy", test: (h) => (h["x-powered-by"] ?? "").toLowerCase().includes("godaddy") },
  { product: "Rocket.net", test: (h) => (h["server"] ?? "").toLowerCase().includes("rocket.net") },
  { product: "Hostinger", test: (h) => "x-hcdn-request-id" in h || Object.keys(h).some((k) => k.startsWith("x-hostinger")) },
  { product: "Nexcess", test: (h) => Object.keys(h).some((k) => k.startsWith("x-nexcess")) },
];

/**
 * slug -> friendly display name for popular plugins. Applied only to plugins
 * we actually detected, so it improves labels with zero false-positive risk.
 * Extend freely.
 */
export const PLUGIN_NAMES: Record<string, string> = {
  akismet: "Akismet",
  jetpack: "Jetpack",
  woocommerce: "WooCommerce",
  elementor: "Elementor",
  "elementor-pro": "Elementor Pro",
  "contact-form-7": "Contact Form 7",
  "wordpress-seo": "Yoast SEO",
  "wordpress-seo-premium": "Yoast SEO Premium",
  "seo-by-rank-math": "Rank Math SEO",
  "all-in-one-seo-pack": "All in One SEO",
  "wp-seopress": "SEOPress",
  "the-seo-framework": "The SEO Framework",
  "google-site-kit": "Site Kit by Google",
  wordfence: "Wordfence Security",
  "better-wp-security": "Solid Security (iThemes)",
  "ithemes-security-pro": "Solid Security Pro",
  "sucuri-scanner": "Sucuri Security",
  "all-in-one-wp-security-and-firewall": "All-In-One Security (AIOS)",
  "wp-super-cache": "WP Super Cache",
  "w3-total-cache": "W3 Total Cache",
  "wp-rocket": "WP Rocket",
  "litespeed-cache": "LiteSpeed Cache",
  "wp-fastest-cache": "WP Fastest Cache",
  autoptimize: "Autoptimize",
  "wp-optimize": "WP-Optimize",
  perfmatters: "Perfmatters",
  "redis-cache": "Redis Object Cache",
  "cache-enabler": "Cache Enabler",
  "wp-smushit": "Smush",
  "ewww-image-optimizer": "EWWW Image Optimizer",
  imagify: "Imagify",
  "shortpixel-image-optimiser": "ShortPixel Image Optimizer",
  "regenerate-thumbnails": "Regenerate Thumbnails",
  "advanced-custom-fields": "Advanced Custom Fields",
  "advanced-custom-fields-pro": "Advanced Custom Fields Pro",
  "secure-custom-fields": "Secure Custom Fields",
  "classic-editor": "Classic Editor",
  "classic-widgets": "Classic Widgets",
  "duplicate-post": "Yoast Duplicate Post",
  redirection: "Redirection",
  "wps-hide-login": "WPS Hide Login",
  updraftplus: "UpdraftPlus",
  backwpup: "BackWPup",
  duplicator: "Duplicator",
  "all-in-one-wp-migration": "All-in-One WP Migration",
  "wpvivid-backuprestore": "WPvivid Backup",
  "mailchimp-for-wp": "Mailchimp for WordPress",
  mailpoet: "MailPoet",
  newsletter: "Newsletter",
  "wp-mail-smtp": "WP Mail SMTP",
  "post-smtp": "Post SMTP",
  "fluent-smtp": "FluentSMTP",
  "easy-wp-smtp": "Easy WP SMTP",
  "wpforms-lite": "WPForms",
  wpforms: "WPForms",
  "ninja-forms": "Ninja Forms",
  gravityforms: "Gravity Forms",
  formidable: "Formidable Forms",
  forminator: "Forminator",
  "everest-forms": "Everest Forms",
  fluentform: "Fluent Forms",
  happyforms: "HappyForms",
  "elementskit-lite": "ElementsKit",
  "header-footer-elementor": "Elementor Header & Footer Builder",
  "essential-addons-for-elementor-lite": "Essential Addons for Elementor",
  "premium-addons-for-elementor": "Premium Addons for Elementor",
  js_composer: "WPBakery Page Builder",
  "siteorigin-panels": "SiteOrigin Page Builder",
  "beaver-builder-lite-version": "Beaver Builder",
  brizy: "Brizy",
  bricks: "Bricks Builder",
  oxygen: "Oxygen Builder",
  "so-widgets-bundle": "SiteOrigin Widgets Bundle",
  tablepress: "TablePress",
  "ninja-tables": "Ninja Tables",
  "the-events-calendar": "The Events Calendar",
  "event-tickets": "Event Tickets",
  "modern-events-calendar-lite": "Modern Events Calendar",
  learnpress: "LearnPress",
  "sfwd-lms": "LearnDash",
  lifterlms: "LifterLMS",
  tutor: "Tutor LMS",
  "sensei-lms": "Sensei LMS",
  buddypress: "BuddyPress",
  bbpress: "bbPress",
  "buddyboss-platform": "BuddyBoss Platform",
  "paid-memberships-pro": "Paid Memberships Pro",
  memberpress: "MemberPress",
  "woocommerce-gateway-stripe": "WooCommerce Stripe Gateway",
  "woocommerce-paypal-payments": "WooCommerce PayPal Payments",
  "woocommerce-payments": "WooPayments",
  "mailchimp-for-woocommerce": "Mailchimp for WooCommerce",
  "dokan-lite": "Dokan",
  "yith-woocommerce-wishlist": "YITH WooCommerce Wishlist",
  cartflows: "CartFlows",
  "woo-variation-swatches": "Variation Swatches for WooCommerce",
  pods: "Pods",
  "code-snippets": "Code Snippets",
  "insert-headers-and-footers": "WPCode",
  "loco-translate": "Loco Translate",
  "translatepress-multilingual": "TranslatePress",
  polylang: "Polylang",
  "sitepress-multilingual-cms": "WPML",
  "really-simple-ssl": "Really Simple SSL",
  "cookie-notice": "Cookie Notice",
  "cookie-law-info": "CookieYes",
  "complianz-gdpr": "Complianz",
  "wp-pagenavi": "WP-PageNavi",
  "breadcrumb-navxt": "Breadcrumb NavXT",
  "broken-link-checker": "Broken Link Checker",
  "google-analytics-for-wordpress": "MonsterInsights",
  "ga-google-analytics": "GA Google Analytics",
  pixelyoursite: "PixelYourSite",
  optinmonster: "OptinMonster",
  "popup-maker": "Popup Maker",
  "wp-defender": "Defender",
  "hummingbird-performance": "Hummingbird",
  "nextgen-gallery": "NextGEN Gallery",
  "envira-gallery-lite": "Envira Gallery",
  foogallery: "FooGallery",
  "modula-best-grid-gallery": "Modula",
  revslider: "Slider Revolution",
  LayerSlider: "LayerSlider",
  "ml-slider": "MetaSlider",
  "smart-slider-3": "Smart Slider 3",
  "profile-builder": "Profile Builder",
  "ultimate-member": "Ultimate Member",
  "user-registration": "User Registration",
  amp: "AMP",
  "disable-comments": "Disable Comments",
  "limit-login-attempts-reloaded": "Limit Login Attempts Reloaded",
  "two-factor": "Two Factor",
  "query-monitor": "Query Monitor",
  "wp-crontrol": "WP Crontrol",
  "user-switching": "User Switching",
  members: "Members",
  "simple-history": "Simple History",
  stream: "Stream",
  "kadence-blocks": "Kadence Blocks",
  "ultimate-addons-for-gutenberg": "Spectra",
  "otter-blocks": "Otter Blocks",
  generateblocks: "GenerateBlocks",
  coblocks: "CoBlocks",
  getwid: "Getwid",
  "stackable-ultimate-gutenberg-blocks": "Stackable",
  "presto-player": "Presto Player",
  "wp-google-maps": "WP Go Maps",
  "wordpress-importer": "WordPress Importer",
  "wp-statistics": "WP Statistics",
  "wp-file-manager": "WP File Manager",
  "wp-reset": "WP Reset",
  "wp-migrate-db": "WP Migrate",
  "google-listings-and-ads": "Google for WooCommerce",
  "jetpack-boost": "Jetpack Boost",
  "antispam-bee": "Antispam Bee",
  "wp-2fa": "WP 2FA",
  "wp-mail-logging": "WP Mail Logging",
  "email-subscribers": "Icegram Express",
  "safe-svg": "Safe SVG",
  "svg-support": "SVG Support",
  "enable-media-replace": "Enable Media Replace",
  "wp-maintenance-mode": "WP Maintenance Mode",
  "coming-soon": "SeedProd",
  "custom-post-type-ui": "Custom Post Type UI",
  "cmb2": "CMB2",
  "duplicate-page": "Duplicate Page",
  "post-types-order": "Post Types Order",
  "table-of-contents-plus": "Table of Contents Plus",
  "easy-table-of-contents": "Easy Table of Contents",
  "wp-recipe-maker": "WP Recipe Maker",
  "webp-express": "WebP Express",
  "instagram-feed": "Smash Balloon Instagram Feed",
  "custom-facebook-feed": "Smash Balloon Facebook Feed",
  "feeds-for-youtube": "Smash Balloon YouTube Feed",
  "add-to-any": "AddToAny Share Buttons",
  "shortpixel-adaptive-images": "ShortPixel Adaptive Images",
  "health-check": "Health Check & Troubleshooting",
  "seo-by-rank-math-pro": "Rank Math SEO PRO",
};

/** slug -> friendly display name for popular themes. */
export const THEME_NAMES: Record<string, string> = {
  twentytwentyfive: "Twenty Twenty-Five",
  twentytwentyfour: "Twenty Twenty-Four",
  twentytwentythree: "Twenty Twenty-Three",
  twentytwentytwo: "Twenty Twenty-Two",
  twentytwentyone: "Twenty Twenty-One",
  twentytwenty: "Twenty Twenty",
  twentynineteen: "Twenty Nineteen",
  twentyseventeen: "Twenty Seventeen",
  twentysixteen: "Twenty Sixteen",
  twentyfifteen: "Twenty Fifteen",
  astra: "Astra",
  generatepress: "GeneratePress",
  oceanwp: "OceanWP",
  kadence: "Kadence",
  "hello-elementor": "Hello Elementor",
  storefront: "Storefront",
  neve: "Neve",
  blocksy: "Blocksy",
  hestia: "Hestia",
  sydney: "Sydney",
  customify: "Customify",
  flatsome: "Flatsome",
  woodmart: "Woodmart",
  betheme: "Betheme",
  the7: "The7",
  Avada: "Avada",
  avada: "Avada",
  enfold: "Enfold",
  bridge: "Bridge",
  salient: "Salient",
  jupiterx: "JupiterX",
  porto: "Porto",
  newspaper: "Newspaper",
  soledad: "Soledad",
  jannah: "Jannah",
  divi: "Divi",
  Divi: "Divi",
  extra: "Extra",
  understrap: "Understrap",
  sage: "Sage",
};

/**
 * Third-party services detected from <script> sources and inline snippets on
 * the homepage. `idRe` (capture group 1) extracts the account/container id.
 */
export const SERVICE_SIGNATURES: {
  name: string;
  category: string;
  re: RegExp;
  idRe?: RegExp;
}[] = [
  { name: "Google Tag Manager", category: "Tag manager", re: /googletagmanager\.com\/(?:gtm|ns)\.|["']GTM-[A-Z0-9]+/i, idRe: /GTM-[A-Z0-9]+/ },
  { name: "Google Analytics 4", category: "Analytics", re: /googletagmanager\.com\/gtag\/js\?id=G-|["']G-[A-Z0-9]{6,}/i, idRe: /G-[A-Z0-9]{6,}/ },
  { name: "Universal Analytics", category: "Analytics", re: /google-analytics\.com\/(?:analytics|ga)\.js|UA-\d{4,}-\d+/i, idRe: /UA-\d{4,}-\d+/ },
  { name: "Google Ads", category: "Ads", re: /googleadservices\.com|googlesyndication\.com|["']AW-\d+/i, idRe: /AW-\d+/ },
  { name: "Facebook Pixel", category: "Ads / pixel", re: /connect\.facebook\.net\/[^"']*\/fbevents\.js|fbq\(\s*["']init/i, idRe: /fbq\(\s*["']init["']\s*,\s*["'](\d{6,})/ },
  { name: "Microsoft Clarity", category: "Analytics", re: /clarity\.ms\/tag\//i, idRe: /clarity\.ms\/tag\/([a-z0-9]+)/i },
  { name: "Hotjar", category: "Analytics", re: /static\.hotjar\.com|hjid\s*[:=]/i, idRe: /hjid\s*[:=]\s*(\d+)/ },
  { name: "LinkedIn Insight", category: "Ads / pixel", re: /snap\.licdn\.com\/li\.lms-analytics|_linkedin_partner_id/i, idRe: /_linkedin_partner_id\s*=\s*["'](\d+)/ },
  { name: "TikTok Pixel", category: "Ads / pixel", re: /analytics\.tiktok\.com|ttq\.load\(/i, idRe: /ttq\.load\(\s*["']([A-Z0-9]+)/i },
  { name: "X (Twitter) Pixel", category: "Ads / pixel", re: /static\.ads-twitter\.com\/uwt\.js|twq\(/i },
  { name: "Pinterest Tag", category: "Ads / pixel", re: /s\.pinimg\.com\/ct\/core|pintrk\(/i },
  { name: "Snapchat Pixel", category: "Ads / pixel", re: /sc-static\.net\/scevent|snaptr\(/i },
  { name: "Yandex Metrica", category: "Analytics", re: /mc\.yandex\.ru\/metrika|ym\(\s*\d+\s*,/i, idRe: /ym\(\s*(\d+)\s*,/ },
  { name: "Matomo", category: "Analytics", re: /matomo\.js|piwik\.js|_paq\.push/i },
  { name: "Segment", category: "Analytics", re: /cdn\.segment\.com\/analytics\.js/i },
  { name: "Cloudflare Web Analytics", category: "Analytics", re: /static\.cloudflareinsights\.com\/beacon/i },
  { name: "HubSpot", category: "Marketing", re: /js\.hs-scripts\.com\/(\d+)|js\.hubspot\.com/i, idRe: /js\.hs-scripts\.com\/(\d+)/ },
  { name: "Intercom", category: "Chat", re: /widget\.intercom\.io|intercomSettings/i },
  { name: "Crisp", category: "Chat", re: /client\.crisp\.chat/i },
  { name: "Tawk.to", category: "Chat", re: /embed\.tawk\.to/i },
  { name: "Zendesk Chat", category: "Chat", re: /static\.zdassets\.com|v2\.zopim\.com/i },
  { name: "Drift", category: "Chat", re: /js\.driftt\.com|drift\.load/i },
  { name: "reCAPTCHA", category: "CAPTCHA", re: /google\.com\/recaptcha|gstatic\.com\/recaptcha/i },
  { name: "hCaptcha", category: "CAPTCHA", re: /hcaptcha\.com\/1\/api\.js/i },
  { name: "Stripe", category: "Payments", re: /js\.stripe\.com/i },
  { name: "PayPal", category: "Payments", re: /paypal\.com\/sdk\/js|paypalobjects\.com/i },
  { name: "Google Fonts", category: "Fonts", re: /fonts\.googleapis\.com/i },
];
